### PR TITLE
I added dimming in PR 180 by mistake, this change will revert the sa…

### PR DESCRIPTION
**Pull request by timorunge**
…me. Add the same time I've made the output a little bit nicer.

Before:
Screenshot 2019-04-10 at 20 58 24

After:
Screenshot 2019-04-10 at 20 58 42

As you can see also the "marked as done" fields are aligned now.

### CODE REVIEW

**Comment by timorunge** [comment]
This is adding another strange behaviour. I'll fix it and re-open the PR.

**Comment by gammons** [comment]
@timorunge I'm not sure if I currently see the dimming you're describing.  Is it currently in `master`?

**Comment by timorunge** [comment]
@gammons Yes. It's currently in master.

**Comment by fcamichel** [comment]
I hope this will be soon merged. The brighter the days, the more it disturbs me.

**Comment by gammons** [comment]
totally forgot about this.

**Pull request merged**
