### PR TITLE
Support for todo.txt file format

### LINKED ISSUE #175: todo.txt support?
I'm wondering if it would be interesting for ultralist to be able to manipulate todo.txt files and be part of that ecosystem.

### PR DESCRIPTION
**Pull request by gammons**
This will allow ultralist to work with [todo.txt](https://github.com/todotxt/todo.txt) files.  

Ultralist will prefer a `todo.txt` file if it sees one in the cwd or home dir.  Otherwise, it will use the standard .todos.json format.

closes #175

### CODE REVIEW

**Comment by gammons** [comment]
@timorunge I think this is ready for a review.  Could you give it a quick look?

**Comment by timorunge** [comment]
@gammons I will take a look tonight my time (GMT+2).

**Comment by timorunge** [comment]
@gammons sorry for the late reply, I was pretty busy and sick afterwards.

Technically it's working fine for me. But actually I personally don't like that I can't use the full power of ultralist while working with a todo.txt file. I think an "import" and "export" functionality in ultralist would fulfill the needs of #175 as well.
Would make it easy to migrate back and forth. 

If you wanna stay with this we should adopt the ScreenPrinter as well and remove the output for due dates.

**Comment by gammons** [comment]
hmm, this makes sense.  there are also other downsides as well:

1. Notes won't be supported
2. I need to write a UUID for each todo if it's synced, adding a bunch of noise to the todo.txt file
3. I also need to write other meta tags like `id` and `archived`

Perhaps an `import` and `export` is the right move.  I agree, I think it will solve the spirit of what #175 is about.

**Comment by timorunge** [comment]
Yeah, I also can imagine something like: If an existing todo.txt file is found ultralist will ask what to do: import the file (in an existing .todos.json file), init ultralist with the todo.txt file in the current directory etc. - the same for the export option. 

This will keep the power of ultralist with all the functionality which is build in but also gives a potential new user the possiblity to test / import / export with todo.txt. 

The core of both applications is the same but for me - personally - todo.txt is a little bit to limited and basically a todo list while ultralist is going into the direction into a GTD app.

**Pull request closed without merging**
