### PR TITLE
Tabby: Fixing most display issues

### PR DESCRIPTION
**Pull request by timorunge**
During my work on #99 I've been facing several issues with the tabwriter, the display of the same etc. - I started to re-work the problems that I've been facing with [tabby](https://github.com/cheynewallace/tabby). 

At the same time I've been removing the "nocolor" and added always a second color option which makes it easier for tabby (or tabwriter) to render everything in the same way.

The output is ways better right now and working like a charm for me. 

Before:
Screenshot 2019-03-29 at 15 50 16

After:
Screenshot 2019-03-29 at 15 54 59

### CODE REVIEW

**Comment by gammons** [comment]
I just started running a build of this locally and it looks _really_ promising.   Do you see any downsides?

**Comment by timorunge** [comment]
No, not beside a little rework of #174. 
In the end tabby is also just another wrapper around tabwriter.

**Comment by gammons** [comment]
I love it.  Do you think this PR is ready to go?

**Comment by timorunge** [comment]
Do it! 
I'll adopt #174 afterwards.

**Comment by gammons** [comment]
Great work @timorunge !

**Comment by timorunge** [comment]
Thanks @gammons.

**Pull request merged**
